sudo: required
services:
 - docker

before_install:
 - docker build -t kevani/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run kevani/react-test npm test -- --coverage

after_success:
 - docker build -t kevani/multi-client ./client
 - docker build -t kevani/multi-nginx ./nginx
 - docker build -t kevani/multi-server ./server
 - docker build -t kevani/multi-worker ./worker

# log in to the docker cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


# take those images and push them to docker hub
 - docker push kevani/multi-client
 - docker push kevani/multi-nginx
 - docker push kevani/multi-server
 - docker push kevani/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-682742850073
  bucket_pah: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure $AWS_SECRET_KEY